name: Cocoapods
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          pod trunk push GrowingAPM.podspec --verbose --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
